# Generated by Django 5.2.7 on 2025-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/300/200?blur=5'),
        ),
    ]
